### PR TITLE
Added the abilty to generate probaiblities for the distributions for a set of values

### PR DESCRIPTION
**Pull request by EchoDel**
Another small PR increasing the functionality of the predictions.

Hopefully it all makes sense, but I think its worth mentioning that I thought that since it takes another parameter it makes sense to be its own method not part of the main predict_dist.

### CODE REVIEW

**Review by StatMixedML — CHANGES_REQUESTED** [review]
Thanks for the PR. Concerning your changes:

- I believe the function `initialize_distributions` makes sense. Can you please change the name into `initialize_distribution` and adjust the function description. Right now it says that it draws n_samples from the predicted distribution, which is not correct.
- I am not quite sure what the input for `generate_probabilities` would be. Would that be, e.g., the mean? Say if the specified distribution is `Gaussian` then the probabilities represent the likelihood of each predicted mean occurring in the given normal distribution. Same goes for the variance or any other moment. What would be a use-case for this information? Also, concerning the code itself, can't we use the predicted parameters as an input and then directly construct the distribution. Also you can use `values = torch.tensor(x).reshape(-1, 1)` directly.

**Comment by EchoDel** [comment]
For my use case I don't care about the samples from the distribution, instead I am getting the probabilities them multiplying them by a feature of the data to get a weighted chance of an event occurring. In this case it makes most sense in the context of a survival model, so with the Weibull or negative binomial but it could be used for others problems when the probabilities matter. 

I've also used this pattern to track the NLL of the model during training on an unseen set for model governance reasons, and to track the NLL through time with new unseen data, again for governance purposes.

I choose to not use the predt_params as an argument and take the booster ect since then the use of the method is identical to the main predict_dist function, but given its isn't available in the main model predict maybe it doesn't make sense to use that signature.

**Comment by StatMixedML** [comment]
Thank you for the comments.

I am currently in the process of completing the unit tests in the upcoming weeks. Once they are finalized, you can modify them accordingly to include a unit test for your specific changes.

**Comment by StatMixedML** [comment]
can you please also add unit-tests for your function, thanks

**Comment by EchoDel** [comment]
I've added unit tests for my method, would you be able to have a review and let me know what you think about it. Thanks

**Pull request closed without merging**
