### PR TITLE
Updated LightGBM to 4.1 and Optuna to 3.3, and the other packages

### PR DESCRIPTION
**Pull request by EchoDel**
Mainly updated LightGBM to the more recent 4.0 release, although optuna was an easy update as well.
My company expects packages to update to the major version before releasing anything.

I ensured that all the test suite ran before submitting the PR

### CODE REVIEW

**Review by StatMixedML — CHANGES_REQUESTED** [review]
Thanks for your PR. Two minor things:

- can you please silent the lgb output during cv and training in `model.py`
- can you please use version 4.1.0 in the `setup.py`

Thanks

**Comment by EchoDel** [comment]
So I've addressed the second comment but I'm not sure its possible to address point 1 for now. 

I've dug into the changelog and code and I can't see anyway to suppress the message.
This is the only mention in the changelog and it doesn't even have the commit message.
[python-package] remove 'fobj' in favor of passing custom objective func...

when you look in the parameters its not really mentioned that you can use a custom objective function, although in the python API its mentioned in the notes that you can do that, but nothing about how to suppress the message.

Finally in the source code the message is created when the objective function isn't the base one with no statement for overriding it.
https://github.com/microsoft/LightGBM/blob/63a882b7400a19485727cc808e4715897e63635a/src/c_api.cpp#L322

**Comment by StatMixedML** [comment]
Thanks for your changes. Can you please open an issue on the LightGBM repo asking how to silence the output. Thanks.

**Comment by EchoDel** [comment]
So I've just seen this issue already exists in the lightgbm repo.

https://github.com/microsoft/LightGBM/issues/6014

**Comment by StatMixedML** [comment]
Does the custom logger verbose output for both .cv and .train?

**Comment by StatMixedML** [comment]
@EchoDel To keep the PR open, can you please check the open issues on the verbosity, thanks.

**Comment by EchoDel** [comment]
Sorry for the delay. Yeh this would fix both since we register it with lgbm at the start

**Comment by StatMixedML** [comment]
@EchoDel Using the suggestion from the lightgbm-issue does not work.

I am using

```python
import lightgbm as lgb
class CustomLogger:
    def init(self):
        self.logger = logging.getLogger('lightgbm_custom')
        self.logger.setLevel(logging.ERROR)

    def info(self, message):
        self.logger.info(message)
    
    def warning(self, message):
        # Suppress warnings by not doing anything
        pass
    
    def error(self, message):
        self.logger.error(message)

lgb.register_logger(CustomLogger())
````

and this gives. The following. Can you please look into this.

```python
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
Exception ignored on calling ctypes callback function: <function _log_callback at 0x0000026D45999760>
Traceback (most recent call last):
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 205, in _log_callback
    _log_native(str(msg.decode('utf-8')))
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 183, in wrapper
    return func(msg)
           ^^^^^^^^^
  File "C:\Users\maerzale\.virtualenvs\LightGBMLSS-8W0JA8W6\Lib\site-packages\lightgbm\basic.py", line 200, in _log_native
    getattr(_LOGGER, _INFO_METHOD_NAME)(msg)
  File "C:\Users\maerzale\AppData\Local\Temp\ipykernel_14620\1534461007.py", line 7, in info
AttributeError: 'CustomLogger' object has no attribute 'logger'
````

**Comment by EchoDel** [comment]
I think this push has got the custom logger working.

There are alot of other packages which have been updated, particularly torch which had an issues in 2.1.0 and 2.0.1 which I could wrap into this PR is you want.

**Comment by StatMixedML** [comment]
@EchoDel Is the custom logger working now? Haven't tested it yet

**Comment by EchoDel** [comment]
Yep, the logger suppresses all the warning messages

**Comment by StatMixedML** [comment]
@EchoDel Thanks for updating the dependencies. Can you please fix the remaining comments so that I can merge the PR. Thanks

**Comment by EchoDel** [comment]
The outstanding requests should be done.

**Pull request merged**
